### ISSUE TITLE
Add tldr.sh

### ISSUE THREAD

**Issue by mr-karan** [captn3m0/hello-cloudflare#1]
[tldr.sh](https://tldr.sh/) also doesn't load on my ISP (Airtel, Delhi). 

![Screenshot_20220107-210547](https://user-images.githubusercontent.com/5689132/148567419-000295a0-e5e0-4869-8867-a7a021df4d91.jpg)

**Comment by captn3m0** [comment]
Had just reported this today: https://github.com/tldr-pages/tldr/issues/7626

**Comment by captn3m0** [comment]
Added
