### ISSUE TITLE
Transparency issue at Airtel 

### ISSUE THREAD

**Issue by kanaiyajain** [captn3m0/hello-cloudflare#9]
**Behavior of Airtel is quite problematic & controversial.**

They are blocking genuine sites without any illegal content matching with name of blocked sites without giving rights of being heard to the domain owner. There is no Notice or public procedures available regarding that to appeal against action taken illegal action taken. 

More over they do not provide any reason, Notice, Govt Order Copy , etc.. to blocked domain owner. This is against Right of Domain Owner. Moreover, They are abusing their dominate position while taking one-way action. 

I have also raised complain regarding that, They failed to provide any written replay & Resolve complain. I have also Demonstrated issue with Airtel Broadband support executive, but he said nothing in our Hand & Failed to provide written reason of doing so. 

_Kindly raise Voice Against such Action by ISP. If any action taken by ISP against any domain, It must be available in public platform/Domain with method to appeal against such act._

**Comment by captn3m0** [comment]
This isn't even just Airtel acting as a end-ISP. This is Airtel doing much worse. 

This issue sounds more relevant to other forums, such as [IFF's Community Forum](https://forum.internetfreedom.in/) which has a [tag for website blocking](https://forum.internetfreedom.in/tags/c/general/5/website-blocking) that might be relevant.

We really need more transparency on these blocks.
